### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by shashi-netra** [autodistill/autodistill-metaclip#2]
This code is released under Creative Commons [Attribution-NonCommercial 4.0 International], any specific reason why this particular module was under this license? Most other autodistill modules are all under Apache (example: [this](https://github.com/autodistill/autodistill-grounding-dino) one) or similar permissive licenses.

Anyway you could consider changing to a more permissive license for usage?

**Comment by yeldarby** [comment]
Autodistill modules follow the same license as the underlying model. I’d love for them to all be Apache 2.0 but unfortunately this isn’t our choice since we didn’t create the model.

The Metaclip repo is [here](https://github.com/facebookresearch/MetaCLIP); if they update the upstream license we’ll gladly update this repo as well.
